---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true
  driver:
    customize:
      memory: 2048

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[admpwd::default]
    verifier:
      inspec_tests:
        - compliance://cis/cis-windows2012r2-level1-memberserver
    attributes:
